---
name: 'SKNUPS Build Project'
description: 'Runs shellcheck and yamllint'

runs:
  using: 'composite'
  steps:

    - name: Execute ShellCheck
      uses: ludeeus/action-shellcheck@cd81f44

    - name: Execute YAMLlint
      shell: bash
      run: yamllint .
